.PHONY: clean All

All:
	@echo "----------Building project:[ prova1 - Debug ]----------"
	@cd "prova1" && "$(MAKE)" -f  "prova1.mk"
clean:
	@echo "----------Cleaning project:[ prova1 - Debug ]----------"
	@cd "prova1" && "$(MAKE)" -f  "prova1.mk" clean
